### ISSUE TITLE
Missing message in Websocket Account Data

### ISSUE THREAD

**Issue by marketfker** [BingX-API/BingX-swap-api-doc#23]
We tried to host more than 1 instances to compare the WS updates, and we found out different Websockets (with same params and listenKey subscription, also tested on same/ different IPs) can receive different messages. For example, Websocket program A only received 4 messages in this second, but program B received 8 messages. Those 4 messages are skipped in the program A and never came back, program A is able to receive some later messages so it is not due to disconnection.

Is this a known issue? We integrated with several other exchanges Websocket data but did not see any similar issue like this, so would like your support. Thanks a lot.

**Comment by Alphadan28** [comment]
> We tried to host more than 1 instances to compare the WS updates, and we found out different Websockets (with same params and listenKey subscription, also tested on same/ different IPs) can receive different messages. For example, Websocket program A only received 4 messages in this second, but program B received 8 messages. Those 4 messages are skipped in the program A and never came back, program A is able to receive some later messages so it is not due to disconnection.
> 
> Is this a known issue? We integrated with several other exchanges Websocket data but did not see any similar issue like this, so would like your support. Thanks a lot.

I have the same problem, i made a little python project which is a little dashboard for my trading but the API is very very unstable and buggy disconects a lot (used binance in this vps for years and never had a single issue) 

also the account data websocket misses data a lot since i use it to send me a telegram whenever a order gets filled but sometimes i recive the message and sometimes i dont, checked the heartbeat and is fine but data just misses sometimes... it pisses me off since i made lot of work just to find that this api is buggy ill have to look for another exchange.

**Comment by marketfker** [comment]
conclusion: just dont use bingx
